// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usermgr.proto

/*
Package usermgr is a generated protocol buffer package.

It is generated from these files:
	usermgr.proto

It has these top-level messages:
	User
	UserRequest
	UserResponse
*/
package usermgr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id     string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Device string `protobuf:"bytes,4,opt,name=device" json:"device,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type UserRequest struct {
	Userid string `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type UserResponse struct {
	Count int32   `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Users []*User `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *UserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "usermgr.User")
	proto.RegisterType((*UserRequest)(nil), "usermgr.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "usermgr.UserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserMgr service

type UserMgrClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	ListUsers(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*UserResponse, error)
}

type userMgrClient struct {
	cc *grpc.ClientConn
}

func NewUserMgrClient(cc *grpc.ClientConn) UserMgrClient {
	return &userMgrClient{cc}
}

func (c *userMgrClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/usermgr.UserMgr/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMgrClient) ListUsers(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/usermgr.UserMgr/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserMgr service

type UserMgrServer interface {
	GetUser(context.Context, *UserRequest) (*UserResponse, error)
	ListUsers(context.Context, *google_protobuf.Empty) (*UserResponse, error)
}

func RegisterUserMgrServer(s *grpc.Server, srv UserMgrServer) {
	s.RegisterService(&_UserMgr_serviceDesc, srv)
}

func _UserMgr_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMgrServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermgr.UserMgr/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMgrServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMgr_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMgrServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermgr.UserMgr/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMgrServer).ListUsers(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usermgr.UserMgr",
	HandlerType: (*UserMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserMgr_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserMgr_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usermgr.proto",
}

func init() { proto.RegisterFile("usermgr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x9a, 0x34, 0x74, 0x6a, 0x3d, 0x0c, 0xb5, 0x2c, 0xf5, 0x52, 0x22, 0x42, 0x4f,
	0x5b, 0xa8, 0x17, 0x0f, 0x9e, 0x04, 0x11, 0x41, 0x2f, 0x01, 0x7f, 0x80, 0x6d, 0xc6, 0xb0, 0x60,
	0xb2, 0x71, 0x77, 0x23, 0x78, 0xf4, 0x9f, 0xcb, 0xce, 0xb4, 0x07, 0x05, 0x6f, 0xfb, 0xde, 0x7e,
	0x6f, 0x67, 0xe7, 0xc1, 0x6c, 0xf0, 0xe4, 0xda, 0xc6, 0xe9, 0xde, 0xd9, 0x60, 0xb1, 0x38, 0xc8,
	0xe5, 0x45, 0x63, 0x6d, 0xf3, 0x4e, 0x1b, 0xb6, 0x77, 0xc3, 0xdb, 0x86, 0xda, 0x3e, 0x7c, 0x09,
	0x55, 0xde, 0x41, 0xf6, 0xe2, 0xc9, 0xe1, 0x19, 0xa4, 0xa6, 0x56, 0xe9, 0x2a, 0x59, 0x4f, 0xaa,
	0xd4, 0xd4, 0x88, 0x90, 0x75, 0xaf, 0x2d, 0xa9, 0x11, 0x3b, 0x7c, 0xc6, 0x05, 0x8c, 0x6b, 0xfa,
	0x34, 0x7b, 0x52, 0x19, 0xbb, 0x07, 0x55, 0x5e, 0xc1, 0x34, 0xbe, 0x51, 0xd1, 0xc7, 0x40, 0x3e,
	0x44, 0x2c, 0x8e, 0x36, 0xb5, 0x4a, 0x04, 0x13, 0x55, 0x3e, 0xc2, 0xa9, 0x60, 0xbe, 0xb7, 0x9d,
	0x27, 0x9c, 0x43, 0xbe, 0xb7, 0x43, 0x17, 0x18, 0xcb, 0x2b, 0x11, 0x78, 0x09, 0x79, 0xe4, 0xbd,
	0x4a, 0x57, 0xa3, 0xf5, 0x74, 0x3b, 0xd3, 0xc7, 0xad, 0x38, 0x2b, 0x77, 0xdb, 0xef, 0x04, 0x8a,
	0xa8, 0x9f, 0x1b, 0x87, 0x37, 0x50, 0x3c, 0x50, 0xe0, 0x25, 0xe6, 0xbf, 0x61, 0xf9, 0xcf, 0xf2,
	0xfc, 0x8f, 0x2b, 0xe3, 0xcb, 0x13, 0xbc, 0x85, 0xc9, 0x93, 0xf1, 0x1c, 0xf5, 0xb8, 0xd0, 0x52,
	0x93, 0x3e, 0xd6, 0xa4, 0xef, 0x63, 0x4d, 0xff, 0xa6, 0x77, 0x63, 0x06, 0xaf, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xea, 0xcc, 0x88, 0x4e, 0x77, 0x01, 0x00, 0x00,
}
