// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sweat.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	sweat.proto

It has these top-level messages:
	Sweat
	SweatStatsRequest
	SweatStatsResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sweat struct {
	CreatedAt       *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Glucose         float32                    `protobuf:"fixed32,2,opt,name=glucose" json:"glucose,omitempty"`
	Chloride        float32                    `protobuf:"fixed32,3,opt,name=chloride" json:"chloride,omitempty"`
	Sodium          float32                    `protobuf:"fixed32,4,opt,name=sodium" json:"sodium,omitempty"`
	Potassium       float32                    `protobuf:"fixed32,5,opt,name=potassium" json:"potassium,omitempty"`
	Magnesium       float32                    `protobuf:"fixed32,6,opt,name=magnesium" json:"magnesium,omitempty"`
	Calcium         float32                    `protobuf:"fixed32,7,opt,name=calcium" json:"calcium,omitempty"`
	Humidity        float32                    `protobuf:"fixed32,8,opt,name=humidity" json:"humidity,omitempty"`
	RoomTemperature float32                    `protobuf:"fixed32,9,opt,name=room_temperature,json=roomTemperature" json:"room_temperature,omitempty"`
	BodyTemperature float32                    `protobuf:"fixed32,10,opt,name=body_temperature,json=bodyTemperature" json:"body_temperature,omitempty"`
	Heartbeat       int32                      `protobuf:"varint,11,opt,name=heartbeat" json:"heartbeat,omitempty"`
}

func (m *Sweat) Reset()                    { *m = Sweat{} }
func (m *Sweat) String() string            { return proto.CompactTextString(m) }
func (*Sweat) ProtoMessage()               {}
func (*Sweat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Sweat) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Sweat) GetGlucose() float32 {
	if m != nil {
		return m.Glucose
	}
	return 0
}

func (m *Sweat) GetChloride() float32 {
	if m != nil {
		return m.Chloride
	}
	return 0
}

func (m *Sweat) GetSodium() float32 {
	if m != nil {
		return m.Sodium
	}
	return 0
}

func (m *Sweat) GetPotassium() float32 {
	if m != nil {
		return m.Potassium
	}
	return 0
}

func (m *Sweat) GetMagnesium() float32 {
	if m != nil {
		return m.Magnesium
	}
	return 0
}

func (m *Sweat) GetCalcium() float32 {
	if m != nil {
		return m.Calcium
	}
	return 0
}

func (m *Sweat) GetHumidity() float32 {
	if m != nil {
		return m.Humidity
	}
	return 0
}

func (m *Sweat) GetRoomTemperature() float32 {
	if m != nil {
		return m.RoomTemperature
	}
	return 0
}

func (m *Sweat) GetBodyTemperature() float32 {
	if m != nil {
		return m.BodyTemperature
	}
	return 0
}

func (m *Sweat) GetHeartbeat() int32 {
	if m != nil {
		return m.Heartbeat
	}
	return 0
}

type SweatStatsRequest struct {
	Userid string `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
}

func (m *SweatStatsRequest) Reset()                    { *m = SweatStatsRequest{} }
func (m *SweatStatsRequest) String() string            { return proto.CompactTextString(m) }
func (*SweatStatsRequest) ProtoMessage()               {}
func (*SweatStatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SweatStatsRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type SweatStatsResponse struct {
	Userid string   `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
	Sweat  []*Sweat `protobuf:"bytes,2,rep,name=sweat" json:"sweat,omitempty"`
}

func (m *SweatStatsResponse) Reset()                    { *m = SweatStatsResponse{} }
func (m *SweatStatsResponse) String() string            { return proto.CompactTextString(m) }
func (*SweatStatsResponse) ProtoMessage()               {}
func (*SweatStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SweatStatsResponse) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *SweatStatsResponse) GetSweat() []*Sweat {
	if m != nil {
		return m.Sweat
	}
	return nil
}

func init() {
	proto.RegisterType((*Sweat)(nil), "api.Sweat")
	proto.RegisterType((*SweatStatsRequest)(nil), "api.SweatStatsRequest")
	proto.RegisterType((*SweatStatsResponse)(nil), "api.SweatStatsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Api service

type ApiClient interface {
	GetSweatStats(ctx context.Context, in *SweatStatsRequest, opts ...grpc.CallOption) (*SweatStatsResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetSweatStats(ctx context.Context, in *SweatStatsRequest, opts ...grpc.CallOption) (*SweatStatsResponse, error) {
	out := new(SweatStatsResponse)
	err := grpc.Invoke(ctx, "/api.Api/GetSweatStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	GetSweatStats(context.Context, *SweatStatsRequest) (*SweatStatsResponse, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_GetSweatStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SweatStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetSweatStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetSweatStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetSweatStats(ctx, req.(*SweatStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSweatStats",
			Handler:    _Api_GetSweatStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sweat.proto",
}

func init() { proto.RegisterFile("sweat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x8b, 0xd5, 0x30,
	0x14, 0x85, 0x6d, 0x6b, 0xdf, 0x4c, 0x6f, 0x11, 0x35, 0x8b, 0x31, 0x94, 0x01, 0x4b, 0x57, 0x15,
	0xa1, 0x03, 0xcf, 0x95, 0xcb, 0x71, 0x23, 0x6e, 0x5c, 0x74, 0x66, 0x3f, 0xa4, 0xed, 0xb5, 0x2f,
	0xd0, 0x4e, 0x62, 0x72, 0x8b, 0xcc, 0x1f, 0x77, 0x2d, 0x49, 0xda, 0xe9, 0x13, 0x71, 0x79, 0xce,
	0xf9, 0x4e, 0x38, 0x5c, 0x02, 0xb9, 0xfd, 0x85, 0x82, 0x1a, 0x6d, 0x14, 0x29, 0x96, 0x08, 0x2d,
	0x8b, 0xf7, 0xa3, 0x52, 0xe3, 0x84, 0x37, 0xde, 0xea, 0x96, 0x1f, 0x37, 0x24, 0x67, 0xb4, 0x24,
	0x66, 0x1d, 0xa8, 0xea, 0x77, 0x0c, 0xe9, 0x9d, 0x6b, 0xb1, 0xcf, 0x00, 0xbd, 0x41, 0x41, 0x38,
	0x3c, 0x08, 0xe2, 0x51, 0x19, 0xd5, 0xf9, 0xb1, 0x68, 0x42, 0xbf, 0xd9, 0xfa, 0xcd, 0xfd, 0xd6,
	0x6f, 0xb3, 0x95, 0xbe, 0x25, 0xc6, 0xe1, 0x62, 0x9c, 0x96, 0x5e, 0x59, 0xe4, 0x71, 0x19, 0xd5,
	0x71, 0xbb, 0x49, 0x56, 0xc0, 0x65, 0x7f, 0x9a, 0x94, 0x91, 0x03, 0xf2, 0xc4, 0x47, 0xcf, 0x9a,
	0x5d, 0xc1, 0xc1, 0xaa, 0x41, 0x2e, 0x33, 0x7f, 0xe9, 0x93, 0x55, 0xb1, 0x6b, 0xc8, 0xb4, 0x22,
	0x61, 0xad, 0x8b, 0x52, 0x1f, 0xed, 0x86, 0x4b, 0x67, 0x31, 0x3e, 0xa2, 0x4f, 0x0f, 0x21, 0x7d,
	0x36, 0xdc, 0x92, 0x5e, 0x4c, 0xbd, 0xcb, 0x2e, 0xc2, 0x92, 0x55, 0xba, 0x25, 0xa7, 0x65, 0x96,
	0x83, 0xa4, 0x27, 0x7e, 0x19, 0x96, 0x6c, 0x9a, 0x7d, 0x80, 0x37, 0x46, 0xa9, 0xf9, 0x81, 0x70,
	0xd6, 0x68, 0x04, 0x2d, 0x06, 0x79, 0xe6, 0x99, 0xd7, 0xce, 0xbf, 0xdf, 0x6d, 0x87, 0x76, 0x6a,
	0x78, 0xfa, 0x0b, 0x85, 0x80, 0x3a, 0xff, 0x1c, 0xbd, 0x86, 0xec, 0x84, 0xc2, 0x50, 0x87, 0x82,
	0x78, 0x5e, 0x46, 0x75, 0xda, 0xee, 0x46, 0xf5, 0x11, 0xde, 0xfa, 0xbb, 0xdf, 0x91, 0x20, 0xdb,
	0xe2, 0xcf, 0x05, 0x2d, 0xb9, 0x93, 0x2c, 0x16, 0x8d, 0x1c, 0xfc, 0xfd, 0xb3, 0x76, 0x55, 0xd5,
	0x77, 0x60, 0xe7, 0xb0, 0xd5, 0xea, 0xd1, 0xe2, 0xff, 0x68, 0x56, 0x42, 0xea, 0x3f, 0x02, 0x8f,
	0xcb, 0xa4, 0xce, 0x8f, 0xd0, 0x08, 0x2d, 0x1b, 0xdf, 0x6f, 0x43, 0x70, 0xfc, 0x06, 0xc9, 0xad,
	0x96, 0xec, 0x0b, 0xbc, 0xfa, 0x8a, 0xb4, 0xbf, 0xcc, 0xae, 0x76, 0xf4, 0x7c, 0x57, 0xf1, 0xee,
	0x1f, 0x3f, 0x4c, 0xa8, 0x5e, 0x74, 0x07, 0xff, 0x35, 0x3e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xa1, 0x26, 0x1b, 0x37, 0x7c, 0x02, 0x00, 0x00,
}
